sequenceDiagram
title SD - Scenarie 3 UC-3: Slet booking

   
    actor Aktør
    participant System

    Ansat->>System: Vælg "Slet booking"
    alt Booking slettet
        System-->>Ansat: Bekræftelse på sletning
    else Fejl (fx ingen adgang eller teknisk fejl)
        System-->>Ansat: Fejlmeddelelse
    end
