sequenceDiagram
title SSD – Scenarie 3: UC-3: Slet booking

  actor aktør
    participant System

    Aktør->>System: Vælg "Slet booking"
    alt Booking slettet
        System-->>Aktør: Bekræftelse på sletning
    else Fejl (fx ingen adgang eller teknisk fejl)
        System-->>Aktør: Fejlmeddelelse
    end
