sequenceDiagram
title SSD – Scenarie 3 UC-4: Rediger booking


    actor Aktør
    participant System

    Aktør->>System: Vælg "Rediger booking"
    Aktør->>System: Indtast ændringer
    alt Booking opdateret
        System-->>Aktør: Bekræftelse på ændring
    else Fejl (fx kapacitet overskredet eller teknisk fejl)
        System-->>Aktør: Fejlmeddelelse
    end
