sequenceDiagram
title SSD – Scenarie 3 UC-4: Rediger booking


    actor Ansat
    participant System

    Ansat->>System: Vælg "Rediger booking"
    Ansat->>System: Indtast ændringer
    alt Booking opdateret
        System-->>Ansat: Bekræftelse på ændring
    else Fejl (fx kapacitet overskredet eller teknisk fejl)
        System-->>Ansat: Fejlmeddelelse
    end
