classDiagram
    class Film {
        Titel
        Varighed
        Premieredato
        Genre
    }

    class Instruktør {
        Navn
    }

    class Biograf {
        Navn
        Adresse
    }

    class Sal {
        Navn
    }

    class Film visning {
        Starttid
    }
   
    Film "1..*" -- "1" Instruktør
    Film visning "1..*" -- "1" Film
    Film visning "0..*" -- "1" Sal
    Sal "1..*" -- "1" Biograf
