classDiagram
    class Film {
        Titel
        Varighed
        Premieredato
        Genre
    }

    class Instruktør {
        Navn
    }

    class Biograf {
        Navn
        Adresse
    }

    class Sal {
        Nummer
        AntalPladser
    }

    class Visning {
        Dato
        Tidspunkt
    }

    

   
    Film "1..*" -- "1..*" Instruktør
    Visning "1..*" -- "1..*" Film
    Visning "1..*" -- "1..*" Sal
    Sal "1..*" -- "1..*" Biograf
