classDiagram
    class Film {
        Titel
        Varighed
    }

    class Genre {
        <<enumeration>>
        Action
        Eventyr
        Biografi
        Komedie
        Kriminalitet
        Drama
        Historie
        Gyser
        Musik
        Mysterie
        Romantik
        Thriller
        Krig
    }

    Film --> Genre
