sequenceDiagram
    actor JensPeter as "Jens Peter"
    participant System as "BiografSystem"

    JensPeter->>System: Klikker "Tilføj ny biograf"
    System-->>JensPeter: Viser biograf vindue

    JensPeter->>System: Intast navn, adress mm. 
    System-->>System: Valider intastning
    System-->>System: Objektet biograf oprettet
    alt Gemt
        System-->>System: Valider gemning
        System-->>JensPeter: bekræftelse
    else Ikke gemt
        System-->>JensPeter: Fejlbesked
    end
