sequenceDiagram
    actor JensPeter as "Aktør"
    participant System as "BiografSystem"

    JensPeter->>System: Klikker "Tilføj ny biograf"
    System-->>JensPeter: Viser biograf vindue

    JensPeter->>System: Intast navn og adresse 
    
    
    alt Gemt
        
        System-->>JensPeter: bekræftelse
    else Ikke gemt
        System-->>JensPeter: Fejlbesked
    end
